spring.application.name=PrepWise

spring.datasource.url=jdbc:postgresql://localhost:5432/prepwise
spring.datasource.username=postgres
spring.datasource.password=Anil@0903

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.initialization-fail-timeout=0

spring.main.lazy-initialization=true
server.port=${PORT:10000}
server.tomcat.connection-timeout=5s

jwt.secret=prepwiseSecretKeyPrepwiseSecretKey123456789

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.health.db.enabled=true

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

logging.level.org.hibernate.SQL=WARN
logging.level.org.springframework=WARN
logging.level.com.zaxxer.hikari=WARN